### ISSUE TITLE
Gặp lỗi java.lang.ClassNotFoundException: com.mysql.jdbc.Driver khi chạy

### ISSUE THREAD

**Issue by hieuvh3011** [Duc-ju/caro-game-client#1]
Em chạy project của bác thì đang gặp lỗi `java.lang.ClassNotFoundException: com.mysql.jdbc.Driver`

Lỗi đang thông báo ở dòng  Class.forName("com.mysql.jdbc.Driver");
![image](https://user-images.githubusercontent.com/69671870/224114210-4bcff7a6-132a-466e-9574-bbc06824807a.png)

Em đã thử khá nhiều cách khi search trên stackoverflow, ví dụ như thay vì "com.mysql.jdbc.Driver" thì dùng "com.mysql.cj.jdbc.Driver", config lại JDK về bản 1.8, import lại lib, ... nhưng vẫn không khắc phục được. Bác có biết lỗi này là gì không vậy. 

Note là em đã chạy đủ database và config lại đường dẫn + user và password chính xác ở file DAO rồi nhé

**Comment by hieuvh3011** [comment]
![image](https://user-images.githubusercontent.com/69671870/224115370-0d303205-3bbc-4d0d-a039-12f032dc77b3.png)
Đây là mysql workbench e đã chạy

**Comment by Duc-ju** [comment]
Bạn import thư viện vào complier của IDE nhé https://github.com/Duc-ju/caro-game-client/blob/main/lib/mysql-connector-java-8.0.13.jar
